INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Ampere', true, 'AMPERE', 'A', 'ElectricCurrent');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Candela', true, 'CANDELA', 'cd', 'LuminousIntensity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Kelvin', true, 'KELVIN', 'K', 'Temperature');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Kilogram', true, 'KILOGRAM', 'kg', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Metre', true, 'METRE', 'm', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Mole', true, 'MOLE', 'mol', 'AmountOfSubstance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Second', true, 'SECOND', 's', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Gram', true, 'GRAM', 'g', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Radian', true, 'RADIAN', 'rad', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Steradian', true, 'STERADIAN', 'sr', 'SolidAngle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Hertz', true, 'HERTZ', 'Hz', 'Frequency');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Newton', true, 'NEWTON', 'N', 'Force');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Pascal', true, 'PASCAL', 'Pa', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Joule', true, 'JOULE', 'J', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Watt', true, 'WATT', 'W', 'Power');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Coulomb', true, 'COULOMB', 'C', 'ElectricCharge');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Volt', true, 'VOLT', 'V', 'ElectricPotential');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Farad', true, 'FARAD', 'F', 'ElectricCapacitance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Ohm', true, 'OHM', 'Ω', 'ElectricResistance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Siemens', true, 'SIEMENS', 'S', 'ElectricConductance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Weber', true, 'WEBER', 'Wb', 'MagneticFlux');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Tesla', true, 'TESLA', 'T', 'MagneticFluxDensity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Henry', true, 'HENRY', 'H', 'ElectricInductance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Celsius', true, 'CELSIUS', '℃', 'Temperature');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Lumen', true, 'LUMEN', 'lm', 'LuminousFlux');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Lux', true, 'LUX', 'lx', 'Illuminance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Becquerel', true, 'BECQUEREL', 'Bq', 'Radioactivity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Gray', true, 'GRAY', 'Gy', 'RadiationDoseAbsorbed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Sievert', true, 'SIEVERT', 'Sv', 'RadiationDoseEffective');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Katal', true, 'KATAL', 'kat', 'CatalyticActivity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Metre per second', true, 'METRE_PER_SECOND', 'm/s', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Metre per square second', true, 'METRE_PER_SQUARE_SECOND', 'm/s²', 'Acceleration');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Square metre', true, 'SQUARE_METRE', 'm²', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Cubic metre', true, 'CUBIC_METRE', '㎥', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Kilometre per hour', true, 'KILOMETRE_PER_HOUR', 'km/h', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Percent', true, 'PERCENT', '%', 'Dimensionless');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Minute', true, 'MINUTE', 'min', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Hour', true, 'HOUR', 'h', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Day', true, 'DAY', 'day', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Week', true, 'WEEK', 'week', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Year', true, 'YEAR', 'year', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (true, 'Litre', true, 'LITRE', 'l', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Meter', true, 'METER', 'm', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Millimeter', true, 'MILLIMETER', 'mm', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Centimeter', true, 'CENTIMETER', 'cm', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Kilometer', true, 'KILOMETER', 'km', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Foot', true, 'FOOT', '(m*3048)/10000', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Furlong', true, 'FURLONG', '((m*3048)/10000)*660', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Yard', true, 'YARD', '((m*3048)/10000)*3', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Inch', true, 'INCH', '((m*3048)/10000)/12', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Mile', true, 'MILE', '(m*1609344)/1000', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Astronomical unit', true, 'ASTRONOMICAL_UNIT', 'm*149597870691', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Fathom', true, 'FATHOM', '((m*3048)/10000)*6', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Mile scandinavian', true, 'MILE_SCANDINAVIAN', 'dakm', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Revolution angle', true, 'REVOLUTION_ANGLE', 'rev', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pi', true, 'PI', 'one*3.1415926535897932384626433832795028', 'Dimensionless');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Meter of mercury column', true, 'METER_OF_MERCURY_COLUMN', '(kPa*1333220)/10000', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Inch hg', true, 'INCH_HG', '(kPa*1333220)/10000·((m*3048)/10000)/12/m', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Degree angle', true, 'DEGREE_ANGLE', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Minute angle', true, 'MINUTE_ANGLE', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Second angle', true, 'SECOND_ANGLE', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Degree', true, 'DEGREE', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Arc minute', true, 'ARC_MINUTE', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Arc second', true, 'ARC_SECOND', '[rad?]', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Square foot', true, 'SQUARE_FOOT', 'sft', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Are', true, 'ARE', 'm²*100', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Hectare', true, 'HECTARE', '(m²*100)*100', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Acre', true, 'ACRE', 'sft*43560', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Square inch', true, 'SQUARE_INCH', '((m*3048)/10000)/12²', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Square yard', true, 'SQUARE_YARD', '((m*3048)/10000)*3²', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Liter', true, 'LITER', 'l', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cubic meter', true, 'CUBIC_METER', '㎥', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cubic inch', true, 'CUBIC_INCH', '((m*3048)/10000)/12³', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Gallon', true, 'GALLON', '(((m*3048)/10000)/12³)*231', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Gallon imperial', true, 'GALLON_IMPERIAL', '(l*454609)/100000', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cubic foot', true, 'CUBIC_FOOT', '(((m*3048)/10000)/12³)*1728', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cubic mile', true, 'CUBIC_MILE', '((((m*3048)/10000)/12³)*1728)*147197952000', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cubic yard', true, 'CUBIC_YARD', '((((m*3048)/10000)/12³)*1728)*27', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Fluid ounce', true, 'FLUID_OUNCE', '((((m*3048)/10000)/12³)*231)/128', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Acre foot', true, 'ACRE_FOOT', '((((m*3048)/10000)/12³)*1728)*43560', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bushel', true, 'BUSHEL', '((((m*3048)/10000)/12³)*215042)/100', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cup', true, 'CUP', '(((((m*3048)/10000)/12³)*231)/128)*8', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Cup metric', true, 'CUP_METRIC', 'ml*250', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pint', true, 'PINT', 'pt', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pint metric', true, 'PINT_METRIC', 'metr. pt', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Quart', true, 'QUART', 'qt', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Minim', true, 'MINIM', 'µl*61.61152', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Teaspoon', true, 'TEASPOON', '(µl*61.61152)*80', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Tablespoon', true, 'TABLESPOON', '((µl*61.61152)*80)*3', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Year julian', true, 'YEAR_JULIAN', 'day*365.25', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Month', true, 'MONTH', '(day*365.25)/12', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Century', true, 'CENTURY', '(day*365.25)*100', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bar', true, 'BAR', 'b', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Tonne', true, 'TONNE', 'kg*1000', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Grain', true, 'GRAIN', '(mg*6479891)/100000', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pound', true, 'POUND', 'lb', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Ounce', true, 'OUNCE', 'oz', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pennyweight troy', true, 'PENNYWEIGHT_TROY', '((mg*6479891)/100000)*24', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Ounce troy', true, 'OUNCE_TROY', '(((mg*6479891)/100000)*24)*20', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Stone', true, 'STONE', 'lb*14', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'C', true, 'C', '(m/s)*299792458', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'G force', true, 'G_FORCE', '(m/s²)*9.80665', 'Acceleration');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Light year', true, 'LIGHT_YEAR', '(m/s)*299792458·day*365.25', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Inch international', true, 'INCH_INTERNATIONAL', '(cm*254)/100', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Foot international', true, 'FOOT_INTERNATIONAL', '((cm*254)/100)*12', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Nautical mile', true, 'NAUTICAL_MILE', 'm*1852', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Knot', true, 'KNOT', 'm*1852/h', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Meter per second', true, 'METER_PER_SECOND', 'm/s', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Mile per hour', true, 'MILE_PER_HOUR', 'mph', 'Speed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Meter per second squared', true, 'METER_PER_SECOND_SQUARED', 'm/s²', 'Acceleration');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Carat', true, 'CARAT', 'ct', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Karat', true, 'KARAT', 'kt', 'Dimensionless');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pound force', true, 'POUND_FORCE', 'lb·(m/s²)*9.80665', 'Force');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Parsec', true, 'PARSEC', 'pc', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Line', true, 'LINE', '((cm*254)/100)/12', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Fahrenheit', true, 'FAHRENHEIT', '((K*5)/9)+459.67', 'Temperature');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Foodcalorie', true, 'FOODCALORIE', 'J*4186.8', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Calorie thermochemical', true, 'CALORIE_THERMOCHEMICAL', '(J*4184)/1000', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Calorie', true, 'CALORIE', '(J*4184)/1000', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Horsepower', true, 'HORSEPOWER', 'lb·((cm*254)/100)*12·(m/s²)*9.80665/s', 'Power');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Pound per square inch', true, 'POUND_PER_SQUARE_INCH', 'lb·(m/s²)*9.80665/(cm*254)/100²', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Sphere', true, 'SPHERE', 'one*3.1415926535897932384626433832795028·sr*4', 'SolidAngle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bit', true, 'BIT', 'bit', 'Information');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Byte', true, 'BYTE', 'byte', 'Information');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bit per second', true, 'BIT_PER_SECOND', 'bit/s', 'InformationRate');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Octet', true, 'OCTET', 'byte', 'Information');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Frame per second', true, 'FRAME_PER_SECOND', '1/s', 'Frequency');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Milligram per deciliter', true, 'MILLIGRAM_PER_DECILITER', 'mg/dl', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Liter per 100kilometers', true, 'LITER_PER_100KILOMETERS', 'km*100/l', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Liter per kilometer', true, 'LITER_PER_KILOMETER', 'km/l', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Mile per gallon', true, 'MILE_PER_GALLON', '(m*1609344)/1000/(((m*3048)/10000)/12³)*231', 'Volume');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Electron volt', null, 'ELECTRON_VOLT', 'eV', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Unified atomic mass', null, 'UNIFIED_ATOMIC_MASS', 'u', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Dalton', null, 'DALTON', 'Da', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Atom', null, 'ATOM', 'mol/602214199000000000000000', 'AmountOfSubstance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Angstrom', null, 'ANGSTROM', 'Å', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bohr radius', null, 'BOHR_RADIUS', 'a0', 'Length');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Barn', null, 'BARN', 'fm²*100', 'Area');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Day sidereal', null, 'DAY_SIDEREAL', 's*86164.09', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Year calendar', null, 'YEAR_CALENDAR', 'day*365', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Year sidereal', null, 'YEAR_SIDEREAL', 's*31558149.54', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Year julien', null, 'YEAR_JULIEN', 's*31557600', 'Time');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Atomic mass', null, 'ATOMIC_MASS', 'kg*1.6605387280149467E-27', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Electron mass', null, 'ELECTRON_MASS', 'kg*9.10938188E-31', 'Mass');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'E', null, 'E', 'e', 'ElectricCharge');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Faraday', null, 'FARADAY', 'C*96485.3414719984', 'ElectricCharge');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Franklin', null, 'FRANKLIN', 'C*3.3356E-10', 'ElectricCharge');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Rankine', null, 'RANKINE', '(K*5)/9', 'Temperature');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Revolution', null, 'REVOLUTION', 'rev', 'Angle');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Standard gravity', null, 'STANDARD_GRAVITY', 'g\u2099', 'Acceleration');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Gal', null, 'GAL', 'cm/s²', 'Acceleration');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Gilbert', null, 'GILBERT', 'one*3.141592653589793·daA/4', 'ElectricCurrent');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Erg', null, 'ERG', 'J/10000000', 'Energy');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Stilb', null, 'STILB', 'cd/cm²', 'Luminance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Lambert', null, 'LAMBERT', 'cd/(one*3.141592653589793·cm²)', 'Luminance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Phot', null, 'PHOT', 'ph', 'Illuminance');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Maxwell', null, 'MAXWELL', 'Wb/100000000', 'MagneticFlux');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Gauss', null, 'GAUSS', 'T/10000', 'MagneticFluxDensity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Oersted', null, 'OERSTED', 'Oe', 'MagneticFieldStrength');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Dyne', null, 'DYNE', 'dyn', 'Force');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Kilogram force', null, 'KILOGRAM_FORCE', 'kgf', 'Force');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Millimetre of mercury', null, 'MILLIMETRE_OF_MERCURY', 'Pa*133.322', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Inch of mercury', null, 'INCH_OF_MERCURY', 'Pa*3386.388', 'Pressure');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Rad', null, 'RAD', 'rd', 'RadiationDoseAbsorbed');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Rem', null, 'REM', 'Sv/100', 'RadiationDoseEffective');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Curie', null, 'CURIE', 'Bq*37000000000', 'Radioactivity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Rutherford', null, 'RUTHERFORD', 'Bq*1000000', 'Radioactivity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Poise', null, 'POISE', 'g/(cm·s)', 'DynamicViscosity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Stokes', null, 'STOKES', 'cm²/s', 'KinematicViscosity');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Frames per second', null, 'FRAMES_PER_SECOND', '1/s', 'Frequency');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Roentgen', null, 'ROENTGEN', 'R', 'IonizingRadiation');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Bel', null, 'BEL', 'B', 'Dimensionless');
INSERT INTO uom (basic, description, display, name, symbol, type) VALUES (null, 'Neper', null, 'NEPER', 'Np', 'Dimensionles');