package org.zs.phm3.auditlog;

public enum ActionType {
    ATTRIBUTE_ADDED,
    ATTRIBUTE_DELETED,
    ATTRIBUTE_UPDATED,
    PROJECT_ADDED,
    PROJECT_DELETED,
    PROJECT_UPDATED,
    SCHEMA_ADDED,
    SCHEMA_DELETED,
    SCHEMA_UPDATED,
    UNITMODEL_ADDED,
    UNITMODEL_UPDATED,
    UNITMODEL_DELETED,
    UNITMODEL_ATTRIBUTE_ADDED,
    UNITMODEL_ATTRIBUTE_UPDATED,
    UNITMODEL_ATTRIBUTE_DELETED,

    UNITTYPE_ADDED,
    UNITTYPE_UPDATED,
    UNITTYPE_DELETED,

    UNIT_ATTRIBUTE_ADDED,
    UNIT_ATTRIBUTE_UPDATED,
    UNIT_ATTRIBUTE_DELETED,

    UNIT_ADDED,
    UNIT_DELETED,
    UNIT_UPDATED,
    USER_ADDED,
    USER_DELETED,
    USER_UPDATED,
    USER_LOGIN,
    USER_LOGOUT,
    TEST;

}

